### ISSUE TITLE
Url does not open up on my phone.

### ISSUE THREAD

**Issue by timtam99** [TheDabblingDuck/ankimote#10]
Hi! I've been trying to use this add-on and when I scan the URL on my Iphone it says "safari cannot open page" I tried it on two different phones, one android and one iphone, and it says the same thing. When i plug the url into my macbook it works but of course this is not helpful for me. Some assistance would be greatly appreciated as I think this is a wonderful and helpful add on. :)

**Comment by TheDabblingDuck** [comment]
Hi. There's a few reasons this could be happening. First make sure you don't have a VPN enabled on your laptop or phone. 

Secondly make sure your phone and laptop are on the same wifi network and that your wifi doesn't block communication across devices. Some public, school, and apartment managed networks block communication so it's best to try it on a home wifi router that you own. 

If none of this works, reply with the address under the QR code, and the **internal** IP address for your phone and computer that you can find using this guide: https://lifehacker.com/how-to-find-your-local-and-external-ip-address-5833108

**Comment by timtam99** [comment]
Thankyou!.192.168.0.22. This is my internal IP address. This is the QR code. http://192.168.0.7:61349/

**Comment by TheDabblingDuck** [comment]
Those addresses look reasonable, the another reason this could happen is the firewall on your computer. 

If you're on windows, try allowing anki access on both public and private networks. Follow this guide https://pureinfotech.com/allow-apps-firewall-windows-10/

**Comment by timtam99** [comment]
Im not on windows, is there another option for ios?

**Comment by TheDabblingDuck** [comment]
What platform is your computer anki on, Mac? 
If your firewall is on you can try letting anki through - 
https://support.apple.com/en-in/guide/mac-help/mh11783/mac

**Comment by TheDabblingDuck** [comment]
Also if your phone is at 192.168.0.22 

Try opening terminal on your computer and typing "ping 192.168.0.22" and hitting enter. This will tell us whether the devices are able to talk to each other over your router

**Comment by timtam99** [comment]
Yea, its on mac. i typed it in and the first thing that comes up in the search engine is "Bogon IP address

**Comment by TheDabblingDuck** [comment]
You'd have to type it into the terminal app on Mac, not your browser

**Comment by timtam99** [comment]
It says "Host is down/ Request timeout for icmp_seq" repeatedly

**Comment by TheDabblingDuck** [comment]
Ok so that shows us that either the devices arent on the same local network / wifi, or that the wifi stops devices from talking to one another. 

I think the best way forward would be to talk to whoever manages your wifi network, or try a different home wifi network.

**Comment by timtam99** [comment]
I see. Thank you.

**Comment by timtam99** [comment]
Tried a different 5g network and it works. :D thank you!
