### ISSUE TITLE
Add on not working or me 

### ISSUE THREAD

**Issue by radioinahole** [TheDabblingDuck/ankimote#11]
Hello
I tried using this add on (looks amazing)- however I keep getting an error message. I have no knowledge of source code (noob here) but I'm desperate to have this add on.
Basically this is what I get:

When loading 'Ankimote - remote to control Anki from your phone':
Traceback (most recent call last):
  File "aqt/addons.py", line 205, in loadAddons
  File "/Users/dbehbehani/Library/Application Support/Anki2/addons21/149004221/__init__.py", line 351, in <module>
    gui_hooks.top_toolbar_did_init_links.append(addlink)
AttributeError: module 'aqt.gui_hooks' has no attribute 'top_toolbar_did_init_links'

Thank you very much

**Comment by TheDabblingDuck** [comment]
Hi,

What version of anki are you using? Can you try updating?

**Comment by radioinahole** [comment]
Hi
thanks for answering
I wish I could but the latest I can update is Version 2.1.20 (which is the Anki version I have now)

I can't update any further cause my laptop software is version  10.10.5 (yosemite)

**Comment by TheDabblingDuck** [comment]
That's the problem. Thanks for letting me know, I'll update the listing on ankiweb so it's no longer compatible with 2.1.20
