### ISSUE TITLE
QR Code doesn't appear

### ISSUE THREAD

**Issue by Wannabbee** [TheDabblingDuck/ankimote#12]
Top & bottom banner blurs out, but the QR code doesn't appear:
![Screenshot1](https://user-images.githubusercontent.com/76991325/103992044-7595fd00-518b-11eb-951e-b4b10107c35f.png)

- Anki Version 2.1.22
- On university Wifi 'eduroam'
- Granted Anki access through firewall
- Disabled other add-ons non-essential to my workflow
- Tried bluetooth connection between Android Galaxy A9 & desktop anki

Tried sharing hotspot from computer to phone, returned error when Ankimote clicked:
![Screenshot2](https://user-images.githubusercontent.com/76991325/103993502-9f502380-518d-11eb-907b-99614c9dd9b2.png)

Bit stumped that I'm missing out on this great addon - any help would be appreciated! :D

**Comment by TheDabblingDuck** [comment]
Hmm that's a set of issue I haven't seen before. We can try to find a solution but it'll probably take a little back and forth.

Try updating your anki to the latest if possible, if not that's fine.

On your university wifi, can you try temporarily disabling all other addons and testing it to see if the QR code pops up? This can help us figure out if the addons you've used to customize/theme your anki home screen are causing this problem.

If it still doesn't show up, can you restart anki fresh (after it being closed for a few minutes) and click Ankimote once. Then find your local ip using this guide ( https://support.microsoft.com/en-us/windows/find-your-ip-address-f21a9bbc-c582-55cd-35e0-73431160a1b9 ) and try visiting that url on your phone with ":61337" at the end. It'll look something like "http://10.0.1.123:61337". This might still not work if your university wifi blocks communication across devices, which is common for public wifi. But let me know what happens.
