### ISSUE TITLE
Bury function

### ISSUE THREAD

**Issue by Jemnakas** [TheDabblingDuck/ankimote#15]
Hello thanks for this add-on it works seamlessly.

How would I be able to add a Bury function in the Python code, pretty much a noob. Apologies if you've answered this before, please direct me to the answer.

Thank you.

**Comment by TheDabblingDuck** [comment]
It's in the sidebar / info panel in the addon config

Bury card: "mw.reviewer.onBuryCard()"

Bury note: "mw.reviewer.onBuryNote()"
