### ISSUE TITLE
Amboss bar not working

### ISSUE THREAD

**Issue by KnightOfCydonia77** [TheDabblingDuck/ankimote#16]
Hi
First of all, thank you for this amazing add-on
As I said in the title, the amboss bar is not working for me, previously it was fine but now it doesn't do anything. Any idea how to fix this?

**Comment by TheDabblingDuck** [comment]
Hi - I'm not able to recreate this issue. I have the latest Anki and amboss addon versions and it seems to be working.

**Comment by KnightOfCydonia77** [comment]
It stopped working once I updated the Amboss add on. I had the version before they integrated the library into anki. I tried reinstalling the old version and got the amboss bar working again, but when I install the last version it stops working. Not sure what's the problem

**Comment by TheDabblingDuck** [comment]
Have fixed and tested it with the 7-26-21 version of the amboss addon. Should work now! Thanks.
