### ISSUE TITLE
Answer Confirmation not showing

### ISSUE THREAD

**Issue by ulytas** [TheDabblingDuck/ankimote#18]
Hello and thank you very much for your wonderful work. 
I'm using Anki 2.1.43 and the answer confirmation doesn't appear at all. I disabled all add-ons beforehand but same result. It works fine with Anki 2.1.35 though. Everything else is working so no big deal. I just wanted to let you know since I didn't see any feedback here or on Ankiweb.
Have a nice day!

**Comment by TheDabblingDuck** [comment]
Thanks for letting me know. - it's fixed in the latest update.
