### ISSUE TITLE
Messes up card scheduling 

### ISSUE THREAD

**Issue by sarahpkdc** [TheDabblingDuck/ankimote#2]
I downloaded ankimote last night. I never fully got it to work. I could get it to turn over the first card but after that it was just completely frozen.

But most troubling was this morning when I opened anki my card scheduling and filtered decks were all messed up. It was as if Anki didn't know what the date was because my "due" cards weren't getting filtered into my filtered decks and when I searched "due" cards in the browser it was only pulling up cards that had a due date of yesterday. Once I deleted ankimote, it all went back to normal.

**Comment by TheDabblingDuck** [comment]
Thanks for reporting! 

That's a really strange issue given that Ankimote doesn't interact with the card database at all. The mostly likely cause is that you have another addon that Ankimote is incompatible with. Any addons modify the answer buttons (again/hard/good/easy) are likely to be incompatible. 

Can you post a list of other addons you have installed? 

Then, can you disable all your other addons and see if the issue persists?

**Comment by sarahpkdc** [comment]
Oh, yeah that makes sense. I definitely have add-ons that modify the answer buttons. 

Do you think that interaction also caused the issue with the card scheduling?

**Comment by TheDabblingDuck** [comment]
Yeah, that's my guess. My addon doesn't touch scheduling, it gets the answer list from a built in anki function and chooses an ease level from that list. I've seen that other addons that modify the answer list (maybe this is how some scheduling addons work) will have problems with ankimote. 

Try it without the addons and see if that works!
