### ISSUE TITLE
Visual feedback on PC not working

### ISSUE THREAD

**Issue by Pettchanashi** [TheDabblingDuck/ankimote#24]
Hi, firstly, I absolutely love the addon. Thank you so much for all the work you put into creating and maintaining it! After one of the more recent Anki updates the visual feedback notifications disappeared completely. I tried reinstalling the addon and removing any other ones in case there was any interference happening, but to no avail. Any ideas on how I could fix that?

**Comment by TheDabblingDuck** [comment]
Thanks for letting me know! This will be fixed in a newer version of the addon. 

For now, you can fix it by opening the anki addons page, clicking ankimote, then 'view addon files', and in the folder that pops up, replace `__init__.py` with the version linked here: https://gofile.io/d/SPHhzl

**Comment by TheDabblingDuck** [comment]
Now fixed in the latest version on ankiweb!
