### ISSUE TITLE
Feature request: bury / suspend

### ISSUE THREAD

**Issue by aPaci95** [TheDabblingDuck/ankimote#3]
It would be fantastic to be able to link bury / suspend a card / note to a gesture / button. Do you think it could be possible?

**Comment by aPaci95** [comment]
Also i was wondering if it could be possible to bind a button to a key / shortcut. For example, i'm currently using rememorize buttons that provides more buttons, and each new button is binded to 5, 6, 7 and so on. It would be relatively easy to be able to use those binding a specific button to a single key (ex. 6). Thank you very much, your addon is really something else!

**Comment by TheDabblingDuck** [comment]
Definitely a good idea to allow custom keyboard shortcuts - I'll look into it when I have time!

**Comment by TheDabblingDuck** [comment]
This will work in the newest version of Ankimote that I just uploaded on Ankiweb. The "check for updates" button in Tools> Addons should find the update.

Then restart anki, go to Tools > Addons > Ankimote > Config, and use the readme in the sidebar to set up custom actions such as suspend/bury.
