### ISSUE TITLE
Slow as a snail 

### ISSUE THREAD

**Issue by alaskakw** [TheDabblingDuck/ankimote#30]
Updated to new version. When I click ankimote, it takes 10+ seconds for QR code to come up. When in tap mode, taps take 10+ seconds to register as well. This is on latest release I downloaded from github 8/17,  5e41f2a.

**Comment by alaskakw** [comment]
Reverting to f72ccf9 fixed the issue.

**Comment by TheDabblingDuck** [comment]
That's hard to interpret since the none of the code for starting the server and having the QR show up has been changed from the 2020 release that works for you. But glad you've found a fix!
