### ISSUE TITLE
Minimal Theme icon

### ISSUE THREAD

**Issue by dochypermoose** [TheDabblingDuck/ankimote#33]
Hey there. Love your add-on. Is there a way to change the Ankimote link to be in line with the [Minimal Theme](https://ankiweb.net/shared/info/867316254)? I was thinking either a remote or a QR code, not sure how I would do that myself though, so figured I'd reach out to the creators for assistance.

![image](https://user-images.githubusercontent.com/25800800/143975886-18a68ee6-8718-4b7e-acd1-9d0c6013f60f.png)

**Comment by TheDabblingDuck** [comment]
Looks like the minimal theme developer added support for theming the ankimote icon yesterday!
