### ISSUE TITLE
Error on Linux Anki 2.1.52

### ISSUE THREAD

**Issue by JejTr** [TheDabblingDuck/ankimote#38]
Hi, I have been using this Add-on on other systems and it has worked perfectly, however when I installed it on anki 2.1.52 it sends this error message and when trying to use the add-on it connects successfully to the android device but then it does not execute any action.
I attach the error code:

_> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 2.1.52 (ab1c2395) Python 3.9.10 Qt 6.3.0 PyQt 6.3.0
> Platform: Linux
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2022-05-23 14:06:05
> Add-ons possibly involved: ⁨Ankimote - remote to control Anki from your phone⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "urllib3.connection", line 174, in _new_conn
>   File "urllib3.util.connection", line 95, in create_connection
>   File "urllib3.util.connection", line 85, in create_connection
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "urllib3.connectionpool", line 703, in urlopen
>   File "urllib3.connectionpool", line 398, in _make_request
>   File "urllib3.connection", line 239, in request
>   File "http.client", line 1285, in request
>   File "http.client", line 1331, in _send_request
>   File "http.client", line 1280, in endheaders
>   File "http.client", line 1040, in _send_output
>   File "http.client", line 980, in send
>   File "urllib3.connection", line 205, in connect
>   File "urllib3.connection", line 186, in _new_conn
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7efd7403daf0>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests.adapters", line 440, in send
>   File "urllib3.connectionpool", line 785, in urlopen
>   File "urllib3.util.retry", line 592, in increment
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd7403daf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "aqt.webview", line 42, in cmd
>   File "aqt.webview", line 149, in _onCmd
>   File "aqt.webview", line 619, in _onBridgeCmd
>   File "aqt.toolbar", line 168, in _linkHandler
>   File "/home/Joshua/.local/share/Anki2/addons21/149004221/__init__.py", line 346, in runRemote
>     requests.post("http://www.google-analytics.com/collect", data=payloadSession)
>   File "requests.api", line 117, in post
>   File "requests.api", line 61, in request
>   File "requests.sessions", line 529, in request
>   File "requests.sessions", line 645, in send
>   File "requests.adapters", line 519, in send
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd7403daf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
>_

**Comment by TheDabblingDuck** [comment]
This seems to be the same as this previous issue, see here for the solution: https://github.com/TheDabblingDuck/ankimote/issues/36

**Comment by JejTr** [comment]
Thank you, it work.
