### ISSUE TITLE
Feature request: replay sound

### ISSUE THREAD

**Issue by KamiGim** [TheDabblingDuck/ankimote#4]
I think it would be very good to be able to replay sound in the card

**Comment by TheDabblingDuck** [comment]
This will work in the newest version of Ankimote that I just uploaded on Ankiweb. The "check for updates" button in Tools> Addons should find the update. 

Then restart anki, go to Tools > Addons > Ankimote > Config,  and replace one of the custom action codes, such as cmd2, with "mw.reviewer.replayAudio()" .

**Comment by KamiGim** [comment]
Thanks a lot. I will go back to review now.
