### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-29: ordinal not in range(128

### ISSUE THREAD

**Issue by PrentissLiu** [TheDabblingDuck/ankimote#5]
`File "/Users/User_Name/Library/Application Support/Anki2/addons21/ankimote/__init__.py", line 163, in handleMessage
    print('Recd: '+msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 24-29: ordinal not in range(128)`

I have run Anki at Chinese environment, I guess there's a problem with the character set.

encode wrong on macOS 10.15,Anki 2.1.26

Thanks for develop this!

**Comment by TheDabblingDuck** [comment]
Sorry, I can only support anki in an English environment at the moment. If I have time to look into this issue in the future and fix it, I will update this bug report.
