### ISSUE TITLE
Only good/show option working on my iPhone

### ISSUE THREAD

**Issue by gelmanovic** [TheDabblingDuck/ankimote#7]
Actually also switch deck option is working. But aside from that I can only get the answer shown, any other functionality is not responding.

Also I wonder if there is a way to type text (there are cards which prompt you to do so)

**Comment by TheDabblingDuck** [comment]
Do you have the button colors addon? My extension isn't compatible with
that one

**Comment by gelmanovic** [comment]
No I have advancedbrowser, review_heatmap, batch editing, advanced previewer and force siblings to show in order

**Comment by TheDabblingDuck** [comment]
Hmm usually people have had that kind of behavior when another addon is
modifying the code for the answer buttons.

Does scrolling work?

If you're motivated to make this work, try disabling your other addons and
seeing if that fixes it. Also if your anki isn't in English, that could be
the problem.

**Comment by gelmanovic** [comment]
Never mind.
The scope which drove me to use your services has voided already.
But that was a very cool smart ass idea nonetheless. 
Unfortunately my passion for Anki relies on the possibility to study anywhere in all most comfty positions I wish to.

**Comment by coco1602** [comment]
Actually, it seems that I am facing the same problem : only the possibilty to show the answer seems to work... And I don't have any addon

**Comment by TheDabblingDuck** [comment]
So you have no other addons and your anki is in English? 

The current version of the addon finds the right button according to the text on it: again, hard, good, easy. Is that how the answer buttons appear for you?

**Comment by coco1602** [comment]
I'm french so my buttons are in french. I didn't knew that the language was important... So the best way would be to turn my Anki to english ?

**Comment by TheDabblingDuck** [comment]
Yes, that would fix this problem. Sorry it doesn't work in other languages

**Comment by coco1602** [comment]
No problem, I just switched to english and it works perfectly ! Thank you !
