### ISSUE TITLE
Visual feedback when not using remote feature

### ISSUE THREAD

**Issue by felipemldias** [TheDabblingDuck/ankimote#8]
Dear Mr./Ms. Duck,

 I apologize for my lack of Github knowledge if this is not the proper place to submit a feature suggestion. This is by far one of the best add-ons out there, and if I could do one thing to make it a little better would be to allow the visual feedback to show at all times, even when the remote is not in use, as when using the keyboard commands. 

I have zero understanding of code, so I don't know if it's a reasonable suggestion, but the visual feedback is so engaging and miles ahead of any other alternative I've found so far that I thought I'd bring it up with you.

Thank you for your kindness and hard work.

Best, 

Felipe

**Comment by TheDabblingDuck** [comment]
Hi Felipe, 

Thanks for your suggestion - many have asked for the same thing. I’ll include this in the next version or perhaps as a separate addon in the future. Time is tight for me right now so it may take a few months.

**Comment by TheDabblingDuck** [comment]
Hi, if you'd like to do this, update to the latest version of the addon, then go to tools>add-ons>ankimote>view files, which should open up the ankimote folder.

Find the file `__init__.py` and remove the following lines:

```
if hasattr(mw.ankimote, 'wssThread'):
        if len(mw.ankimote.wssThread.server.connections)==0:
            return
```

And then restart Anki to load the changes.

I'm not going to make the feedback show at all times by default as other users (#25) have mentioned they'd like the feedback to show only when using ankimote.
